### ISSUE TITLE
IVR benchmark: Fix greeting task on IVRBenchmark Autopilot

### ISSUE THREAD

**Issue by dmarvp** [bespoken/nlp-benchmark#3]
### Summary
We've set up an Autopilot bot here: https://www.twilio.com/console/autopilot/IVRBenchmark
It is tied to the following number: +1 650 469 8776
If we use the simulator here: https://www.twilio.com/console/autopilot/IVRBenchmark/simulator it works fine.
However, when calling from a phone it starts directly with a fallback saying: Sorry, I didn't get that.

We need to fix it so that the greeting task is invoked properly when a user calls.

**Comment by ecruzado** [comment]
getting always the greeting intent at first using Twilio number

**Comment by dmarvp** [comment]
Verified with bst.
