### ISSUE TITLE
IVR Benchmark: DialogFlow endpoint

### ISSUE THREAD

**Issue by dmarvp** [bespoken/nlp-benchmark#6]
### Summary
We want to retrieve the ASR results from the different IVR providers starting with DialogFlow. For this, we'll start an express server with a `/dialogflow` endpoint. We've already configured a DialogFlow Phone Gateway integration that will call the new endpoint.

The endpoint should take the `testNumber` and `phrase` parameters from the DialogFlow request and pass them to a common class. This class will:

- Query the Benchmark database and look for the latest run for the dialogFlow platform with the same `testNumber`.
- Compare the expected phrase on the database with the `phrase` parameter sent to the endpoint.
- Update the success and error fields accordingly
- Save the full request in a `rawRequest` field as well.

*NOTE: We might need to do comparison using Fuse.js since DialogFlow introduces punctuation signs to their `@any` slot types.

### Background
The number to call is: +1 646-838-2369
This is how an interaction goes:
```
- US: $DIAL
- DF: Welcome to the Bespoken IVR Benchmark for Dialogflow. Please, say your utterance now.
- US: Number {testNumber}. Expected phrase: {phrase}
- DF: Thanks! your input was recorded. Goodbye!
```

The `testNumber` and `phrase` slots will be filled by DialogFlow and a request will be made to our endpoint that looks like this:

```json
{
      "responseId": "cba608dc-f54e-48ac-83d8-e0c526574887-fddac391",
      "queryResult": {
        "queryText": "Number 300 expected phrase. Hey, how are you doing?",
        "parameters": {
          "testNumber": 300.0,
          "phrase": ". Hey, how are you doing?"
        },
        "allRequiredParamsPresent": true,
        "fulfillmentText": "Thanks! Your input was recorded. Goodbye!",
        "fulfillmentMessages": [{
          "text": {
            "text": ["Thanks! Your input was recorded. Goodbye!"]
          }
        }],
        "outputContexts": [{
          "name": "projects/ivrbenchmarkagent-pyhr/agent/sessions/119FtGvfJBPTcivqvCH4plDJw/contexts/__system_counters__",
          "parameters": {
            "no-input": 0.0,
            "no-match": 0.0,
            "testNumber": 300.0,
            "testNumber.original": "300",
            "phrase": ". Hey, how are you doing?",
            "phrase.original": ". Hey, how are you doing?"
          }
        }],
        "intent": {
          "name": "projects/ivrbenchmarkagent-pyhr/agent/intents/0853b374-f025-4df8-ae70-3943ec89c9ea",
          "displayName": "BenchmarkIntent"
        },
        "intentDetectionConfidence": 0.6666702,
        "languageCode": "en"
      },
      "originalDetectIntentRequest": {
        "source": "GOOGLE_TELEPHONY",
        "payload": {
          "telephony": {
            "caller_id": "REDACTED_IN_STANDARD_TIER_AGENT"
          }
        }
      },
      "session": "projects/ivrbenchmarkagent-pyhr/agent/sessions/119FtGvfJBPTcivqvCH4plDJw"
    }
```

Example on Cloudwatch:
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252FIVRBenchmark/log-events/2020$252F10$252F16$252F$255B$2524LATEST$255Dafe722a30ae4422e8c45e154b50be29c

*Note: That log comes from using API Gateway to invoke a lambda function. We won't use that for this endpoint, so we will only get the request that I posted above.

**Comment by dmarvp** [comment]
@moisesnandres refer to the latest comment on #5 . That would replace the part about having a common class, as it would be assumed by the `interceptResult` method.

**Comment by ecruzado** [comment]
https://github.com/bespoken/ivr-benchmark/pulls
