### ISSUE TITLE
IVR Benchmark: Amazon Connect endpoint

### ISSUE THREAD

**Issue by dmarvp** [bespoken/nlp-benchmark#7]
### Summary
As in #6, we'll add a `/connect` endpoint that will handle requests coming from Amazon Connect (with Lex) containing their ASR result.

### Background
- The number to call is: +1 360-526-033
- This is how a call looks like:
```
- US: $DIAL
- DF: Welcome to the Bespoken IVR Benchmark for Amazon Connect. Please, say your utterance now.
- DF: Beep.
- US: Number {testNumber}. Expected phrase: {phrase}
- DF: Got it Thanks! 
- DF: Thanks! your input was recorded. Goodbye!
```
- Amazon Lex only works with Lambdas. This means we can't directly call our endpoint. Instead, we'll have a lamdba that just passes the request to our endpoint.
- Lex doesn't have a `@any` slot type. They do have a number type, but no way to create sample utterances that would work to get the expected phrase along with the testNumber,  so we can only rely on not adding slot types and working with the full transcript found on the `inputTranscript` parameter.
- For Lex, we should convert the number from words to an actual number: https://www.npmjs.com/package/words-to-numbers
- Once again, the expected phrase should be analyzed using Fuse.js
- The number and phrase will then go through the common class mentioned on #6 

This is how a request looks like:

```javascript
{
  messageVersion: '1.0',
  invocationSource: 'FulfillmentCodeHook',
  userId: '06af5e2d-e845-4125-bbb2-f587ca6b57e4',
  sessionAttributes: {},
  requestAttributes: { 'x-amz-lex:accept-content-types': 'PlainText,SSML' },
  bot: { name: 'IVRBenchmark', alias: 'IVRBenchmark', version: '4' },
  outputDialogMode: 'Text',
  currentIntent: {
    name: 'IVRFallback',
    slots: {},
    slotDetails: {},
    confirmationStatus: 'None',
    nluIntentConfidenceScore: null
  },
  alternativeIntents: [
    {
      name: 'HelloIntent',
      slots: {},
      slotDetails: {},
      confirmationStatus: 'None',
      nluIntentConfidenceScore: 0.28
    }
  ],
  inputTranscript: 'number one hundred twenty four expected phrase i want to try the lacson connected to gratian',
  recentIntentSummaryView: null,
  sentimentResponse: null,
  kendraResponse: null
}

```

Example on Cloudwatch:
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252FIVRBenchmark/log-events/2020$252F10$252F18$252F$255B$2524LATEST$255D6dd7f5da6a66496686d13dd721246c17

**Comment by ecruzado** [comment]
https://github.com/bespoken/ivr-benchmark/commit/7f598d1e745d982fdc34b314388fb5fb4ae1e374
