### ISSUE TITLE
IVR Benchmark: Twilio endpoint

### ISSUE THREAD

**Issue by dmarvp** [bespoken/nlp-benchmark#8]
### Summary
As in #6 and #7, we'll create an endpoint `/twilio` that will extract the test number and phrase from calling Twilio. 

### Background
The number to call is: +1 650 469 8776

As with DialogFlow, we can extract the number and phrase from a single request made to our endpoint by Twilio. However, we are not able to get in a single utterance. Instead, Twilio will ask a question for each slot. 

This is how a call to Twilio looks like:
```
- US: $DIAL
- TW: Welcome to the Bespoken IVR Benchmark for Twilio. What's the test number?
- US: {test_number}. 
- TW: What's the expected phrase?
- US: {expected_phrase}
```

For this to work, instead of sending a single phrase for the record, we'll load the expected phrase as the utterance and use the `interceptRequest` method to include the test number first as a separate utterance.

This is how a request made to our endpoint would look like:

>CurrentTask=BenchmarkIntent&CurrentInput=Hello, how are you?&DialogueSid=UK853641c3d6cf4ccb8d186757e326e2d8&Memory={"twilio":{"voice":{"To":"","From":"client:Anonymous","CallSid":"CA24f0e3fb901d37aa1f9568d7da8bd44b","Direction":"inbound"},"collected_data":{"benchmark_questions":{"answers":{"test_number":{"confirm_attempts":0,"answer":"129","filled":true,"type":"Twilio.NUMBER","confirmed":false,"validate_attempts":1,"attempts":1},"expected_phrase":{"answer":"Hello, how are you?","filled":true,"attempts":1,"validate_attempts":1,"confirm_attempts":0,"confirmed":false,"media":null}},"date_completed":"2020-10-16T18:53:11Z","date_started":"2020-10-16T18:52:58Z","status":"complete"}}}}&DialoguePayloadUrl=https://autopilot.twilio.com/v1/Assistants/UAf20ba5c38018a8778e59e87004b3df76/Dialogues/UK853641c3d6cf4ccb8d186757e326e2d8&Channel=voice&NextBestTask=&CurrentTaskConfidence=&AssistantSid=UAf20ba5c38018a8778e59e87004b3df76&UserIdentifier=client:Anonymous&AccountSid=AC946b7de473c03fbef3e1c7e7e48fc72b

The values we are looking for are inside `collected_data.benchmark_questions.answers.{parameter}.answer`

Example in Cloudwatch:
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252FIVRBenchmark/log-events/2020$252F10$252F16$252F$255B$2524LATEST$255Db6f1e8e9528942ee9ee583e0f21169f4

*Note: that log comes from using API Gateway to call a lambda function, which we won't do since we will be calling in our own endpoint. It is possible that the request comes in base64.

**Comment by ecruzado** [comment]
https://github.com/bespoken/ivr-benchmark/commit/19aa932a458ee75f06e77b4743dd9213fb092237
